## Root Logger
rootLogger=DEBUG, STDOUT

log4j.logger.it.brunasti.dataTools=DEBUG, STDOUT

# Direct log messages to stdout
appender.console.name = STDOUT
appender.console.type = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %c{1} - %msg%n
